version: 2

build:
  os: ubuntu-22.04  # Specify a valid operating system
  tools:
    python: "3.8"  # Specify the Python version you want to use

python:
  version: 3.12.6
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs  # Ensure you have a 'docs' extra requirement in your setup.py or requirements.txt

sphinx:
  builder: html
  configuration: docs/conf.py 
  fail_on_warning: true
