name: Basic GitHub Actions Workflow

on:  
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  basic-job:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo "Hello, world!"

